//==================================================
// This file contains the Excluded objects
// Generated By User: oille
// Format Version: 2
// Date: Mon Dec  4 10:04:42 2023
// ExclMode: default
//==================================================
CHECKSUM: "3919593816 2691150410"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.PROTOCOL_CONTROL_INST.PROTOCOL_CONTROL_FSM_INST
Fsm CURR_STATE "2691150410"
Transition S_PC_IDLE->S_PC_ACT_ERR_FLAG "2->29"
Fsm CURR_STATE "2691150410"
Transition S_PC_INTEGRATING->S_PC_ACT_ERR_FLAG "1->29"
Fsm CURR_STATE "2691150410"
Transition S_PC_INTERMISSION->S_PC_ACT_ERR_FLAG "25->29"
Fsm CURR_STATE "2691150410"
Transition S_PC_OFF->S_PC_ACT_ERR_FLAG "0->29"
Fsm CURR_STATE "2691150410"
Transition S_PC_OVR_FLAG_TOO_LONG->S_PC_ACT_ERR_FLAG "33->29"
Fsm CURR_STATE "2691150410"
Transition S_PC_PAS_ERR_FLAG->S_PC_ACT_ERR_FLAG "30->29"
Fsm CURR_STATE "2691150410"
Transition S_PC_REINTEGRATING->S_PC_ACT_ERR_FLAG "28->29"
Fsm CURR_STATE "2691150410"
Transition S_PC_REINTEGRATING_WAIT->S_PC_ACT_ERR_FLAG "27->29"
Fsm CURR_STATE "2691150410"
Transition S_PC_SOF->S_PC_ACT_ERR_FLAG "3->29"
Fsm CURR_STATE "2691150410"
Transition S_PC_SUSPEND->S_PC_ACT_ERR_FLAG "26->29"
Fsm CURR_STATE "2691150410"
Transition S_PC_ERR_FLAG_TOO_LONG->S_PC_INTEGRATING "32->1"
Fsm CURR_STATE "2691150410"
Transition S_PC_IDLE->S_PC_INTEGRATING "2->1"
Fsm CURR_STATE "2691150410"
Transition S_PC_OVR_FLAG_TOO_LONG->S_PC_INTEGRATING "33->1"
Fsm CURR_STATE "2691150410"
Transition S_PC_PAS_ERR_FLAG->S_PC_INTEGRATING "30->1"
Fsm CURR_STATE "2691150410"
Transition S_PC_REINTEGRATING->S_PC_INTEGRATING "28->1"
Fsm CURR_STATE "2691150410"
Transition S_PC_REINTEGRATING_WAIT->S_PC_INTEGRATING "27->1"
Fsm CURR_STATE "2691150410"
Transition S_PC_SOF->S_PC_INTEGRATING "3->1"
Fsm CURR_STATE "2691150410"
Transition S_PC_SUSPEND->S_PC_INTEGRATING "26->1"
Fsm CURR_STATE "2691150410"
Transition S_PC_SUSPEND->S_PC_PAS_ERR_FLAG "26->30"
Fsm CURR_STATE "2691150410"
Transition S_PC_SOF->S_PC_PAS_ERR_FLAG "3->30"
Fsm CURR_STATE "2691150410"
Transition S_PC_REINTEGRATING_WAIT->S_PC_PAS_ERR_FLAG "27->30"
Fsm CURR_STATE "2691150410"
Transition S_PC_REINTEGRATING->S_PC_PAS_ERR_FLAG "28->30"
Fsm CURR_STATE "2691150410"
Transition S_PC_OVR_FLAG_TOO_LONG->S_PC_PAS_ERR_FLAG "33->30"
Fsm CURR_STATE "2691150410"
Transition S_PC_IDLE->S_PC_PAS_ERR_FLAG "2->30"
Fsm CURR_STATE "2691150410"
Transition S_PC_ERR_FLAG_TOO_LONG->S_PC_PAS_ERR_FLAG "32->30"
Fsm CURR_STATE "2691150410"
Transition S_PC_ERR_FLAG_TOO_LONG->S_PC_ACT_ERR_FLAG "32->29"
CHECKSUM: "2746243366 3668036399"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN(0).TXT_BUFFER_INST.TXT_BUFFER_FSM_INST
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 36  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1"
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 38  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1" (1 "00")
CHECKSUM: "2746243366 3668036399"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN(1).TXT_BUFFER_INST.TXT_BUFFER_FSM_INST
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 36  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1"
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 38  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1" (1 "00")
CHECKSUM: "2746243366 3668036399"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN(2).TXT_BUFFER_INST.TXT_BUFFER_FSM_INST
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 36  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1"
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 38  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1" (1 "00")
CHECKSUM: "2746243366 3668036399"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN(3).TXT_BUFFER_INST.TXT_BUFFER_FSM_INST
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 36  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1"
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 38  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1" (1 "00")
CHECKSUM: "2746243366 3668036399"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN(4).TXT_BUFFER_INST.TXT_BUFFER_FSM_INST
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 36  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1"
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 38  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1" (1 "00")
CHECKSUM: "2746243366 3668036399"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN(5).TXT_BUFFER_INST.TXT_BUFFER_FSM_INST
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 36  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1"
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 38  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1" (1 "00")
CHECKSUM: "2746243366 3668036399"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN(6).TXT_BUFFER_INST.TXT_BUFFER_FSM_INST
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 36  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1"
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 38  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1" (1 "00")
CHECKSUM: "2746243366 3668036399"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN(7).TXT_BUFFER_INST.TXT_BUFFER_FSM_INST
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 36  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1"
ANNOTATION: " Unreachable due to PC FSM always setting either valid, arb lost, err or failed. "
Condition 38  "((TXTB_HW_CMD.ERR = '1') OR (TXTB_HW_CMD.ARBL = '1')) 1 -1" (1 "00")
