//==================================================
// This file contains the Excluded objects
// Generated By User: oille
// Format Version: 2
// Date: Mon Dec  4 09:39:17 2023
// ExclMode: default
//==================================================
CHECKSUM: "517785777 1653484585"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.RX_BUFFER_INST.RX_BUFFER_POINTERS_INST
ANNOTATION: "Verified by block level unit test."
Block 31 "rx_mem_free_i_i <= rx_mem_free_raw_inc_1;"
ANNOTATION: "Verified by block level unit test."
Block 24 "rx_mem_free_raw <= rx_mem_free_i_inc_1;"
CHECKSUM: "2094380965 1300362865"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.RX_BUFFER_INST.RX_BUFFER_FSM_INST
ANNOTATION: "Verified by block level unit test."
Block 5 "next_state <= s_rxb_idle;"
