//==================================================
// This file contains the Excluded objects
// Generated By User: oille
// Format Version: 2
// Date: Tue Nov 14 23:26:05 2023
// ExclMode: default
//==================================================
CHECKSUM: "747525153"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.BUS_SAMPLING_INST.INLINED_PSL
CHECKSUM: "2270156498"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.PRESCALER_INST.INLINED_PSL
CHECKSUM: "4209074626"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.PROTOCOL_CONTROL_INST.PROTOCOL_CONTROL_FSM_INST.INLINED_PSL
CHECKSUM: "1047503161"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.MEMORY_REGISTERS_INST.INLINED_PSL
CHECKSUM: "2348786537"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TX_ARBITRATOR_INST.INLINED_PSL
CHECKSUM: "2594111837"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.PROTOCOL_CONTROL_INST.RETRANSMITT_COUNTER_INST.INLINED_PSL
CHECKSUM: "258925685"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.BUS_SAMPLING_INST.SSP_GENERATOR_INST.INLINED_PSL
CHECKSUM: "1545394481"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.BIT_DESTUFFING_INST.INLINED_PSL
CHECKSUM: "1896333073"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.PROTOCOL_CONTROL_INST.INLINED_PSL
CHECKSUM: "4000665440"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.RX_BUFFER_INST.RX_BUFFER_RAM_INST.INLINED_PSL
CHECKSUM: "2336123282"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.RX_BUFFER_INST.RX_BUFFER_POINTERS_INST.INLINED_PSL
CHECKSUM: "3374679215"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.PRESCALER_INST.SYNCHRONISATION_CHECKER_INST.INLINED_PSL
CHECKSUM: "313449797"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.INLINED_PSL
CHECKSUM: "891400667"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.RX_BUFFER_INST.RX_BUFFER_FSM_INST.INLINED_PSL
CHECKSUM: "3606770058"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.INLINED_PSL
CHECKSUM: "1425166142"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.PRESCALER_INST.BIT_SEGMENT_METER_DBT_INST.INLINED_PSL
CHECKSUM: "1425166142"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.PRESCALER_INST.BIT_SEGMENT_METER_NBT_INST.INLINED_PSL
CHECKSUM: "2532283662"
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[7].TXT_BUFFER_INST.TXT_BUFFER_RAM_INST.INLINED_PSL
CHECKSUM: "2532283662"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[6].TXT_BUFFER_INST.TXT_BUFFER_RAM_INST.INLINED_PSL
CHECKSUM: "2532283662"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[5].TXT_BUFFER_INST.TXT_BUFFER_RAM_INST.INLINED_PSL
CHECKSUM: "2532283662"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[4].TXT_BUFFER_INST.TXT_BUFFER_RAM_INST.INLINED_PSL
CHECKSUM: "2532283662"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[3].TXT_BUFFER_INST.TXT_BUFFER_RAM_INST.INLINED_PSL
CHECKSUM: "2532283662"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[2].TXT_BUFFER_INST.TXT_BUFFER_RAM_INST.INLINED_PSL
CHECKSUM: "2532283662"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[1].TXT_BUFFER_INST.TXT_BUFFER_RAM_INST.INLINED_PSL
CHECKSUM: "2532283662"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[0].TXT_BUFFER_INST.TXT_BUFFER_RAM_INST.INLINED_PSL
CHECKSUM: "2394908449"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.INT_MANAGER_INST.INLINED_PSL
CHECKSUM: "3483315454"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.BUS_SAMPLING_INST.BIT_ERR_DETECTOR_INST.INLINED_PSL
CHECKSUM: "3515286224"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.FAULT_CONFINEMENT_INST.FAULT_CONFINEMENT_RULES_INST.INLINED_PSL
CHECKSUM: "3739313909"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.CAN_CRC_INST.CRC_CALC_21_RX_INST.INLINED_PSL
CHECKSUM: "3739313909"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.CAN_CRC_INST.CRC_CALC_17_RX_INST.INLINED_PSL
CHECKSUM: "3739313909"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.CAN_CRC_INST.CRC_CALC_15_INST.INLINED_PSL
CHECKSUM: "4125648115"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.PROTOCOL_CONTROL_INST.RX_SHIFT_REG_INST.INLINED_PSL
CHECKSUM: "2176579395"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.PROTOCOL_CONTROL_INST.REINTEGRATION_COUNTER_INST.INLINED_PSL
CHECKSUM: "221363224"
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[7].TXT_BUFFER_INST.TXT_BUFFER_FSM_INST.INLINED_PSL
CHECKSUM: "221363224"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[6].TXT_BUFFER_INST.TXT_BUFFER_FSM_INST.INLINED_PSL
CHECKSUM: "221363224"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[5].TXT_BUFFER_INST.TXT_BUFFER_FSM_INST.INLINED_PSL
CHECKSUM: "221363224"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[4].TXT_BUFFER_INST.TXT_BUFFER_FSM_INST.INLINED_PSL
CHECKSUM: "221363224"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[3].TXT_BUFFER_INST.TXT_BUFFER_FSM_INST.INLINED_PSL
CHECKSUM: "221363224"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[2].TXT_BUFFER_INST.TXT_BUFFER_FSM_INST.INLINED_PSL
CHECKSUM: "221363224"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[1].TXT_BUFFER_INST.TXT_BUFFER_FSM_INST.INLINED_PSL
CHECKSUM: "221363224"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[0].TXT_BUFFER_INST.TXT_BUFFER_FSM_INST.INLINED_PSL
CHECKSUM: "4032092913"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.PROTOCOL_CONTROL_INST.CONTROL_COUNTER_INST.INLINED_PSL
CHECKSUM: "802881316"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.PRESCALER_INST.SEGMENT_END_DETECTOR_INST.INLINED_PSL
CHECKSUM: "2074431189"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.BUS_SAMPLING_INST.TRV_DELAY_MEASUREMENT_INST.INLINED_PSL
CHECKSUM: "4046248047"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.BUS_SAMPLING_INST.TX_DATA_CACHE_INST.INLINED_PSL
CHECKSUM: "3574979556"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[7].TXT_BUFFER_INST.INLINED_PSL
CHECKSUM: "3574979556"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[6].TXT_BUFFER_INST.INLINED_PSL
CHECKSUM: "3574979556"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[5].TXT_BUFFER_INST.INLINED_PSL
CHECKSUM: "3574979556"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[4].TXT_BUFFER_INST.INLINED_PSL
CHECKSUM: "3574979556"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[3].TXT_BUFFER_INST.INLINED_PSL
CHECKSUM: "3574979556"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[2].TXT_BUFFER_INST.INLINED_PSL
CHECKSUM: "3574979556"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[1].TXT_BUFFER_INST.INLINED_PSL
CHECKSUM: "3574979556"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TXT_BUF_COMP_GEN[0].TXT_BUFFER_INST.INLINED_PSL
CHECKSUM: "2600360639"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.BUS_SAMPLING_INST.DATA_EDGE_DETECTOR_INST.INLINED_PSL
CHECKSUM: "1559196190"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.BUS_TRAFFIC_CTRS_GEN.BUS_TRAFFIC_COUNTERS_INST.INLINED_PSL
CHECKSUM: "3156185221"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.PROTOCOL_CONTROL_INST.ERR_DETECTOR_INST.INLINED_PSL
CHECKSUM: "665751105"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.PRESCALER_INST.TRIGGER_GENERATOR_INST.INLINED_PSL
CHECKSUM: "3815011450"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.FAULT_CONFINEMENT_INST.ERR_COUNTERS_INST.INLINED_PSL
CHECKSUM: "963933153"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.RX_BUFFER_INST.INLINED_PSL
CHECKSUM: "4105039858"
ANNOTATION: " Excluding PSL asserts. "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.PROTOCOL_CONTROL_INST.TX_SHIFT_REG_INST.INLINED_PSL
CHECKSUM: "4227603430"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.TX_ARBITRATOR_INST.TX_ARBITRATOR_FSM_INST.INLINED_PSL
CHECKSUM: "3033193814"
ANNOTATION: "  Excluding PSL asserts.  "
INSTANCE:TB_TOP_CTU_CAN_FD.DUT.CAN_CORE_INST.OPERATION_CONTROL_INST.INLINED_PSL
CHECKSUM: "2632252831 1630422902"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.MEMORY_REGISTERS_INST.CONTROL_REGISTERS_REG_MAP_COMP
ANNOTATION: " PSLs are excluded "
Condition 1  "((CS = '1') AND (READ = '1') AND (REG_SEL(0) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 121  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(32) = '1') AND ((BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 111  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(30) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 107  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(29) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 101  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(26) = '1') AND (BE(2) = '1')) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 89  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(23) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 85  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(22) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 81  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(21) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 77  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(20) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 73  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(19) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 69  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(18) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 65  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(17) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 61  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(16) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 57  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(15) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 55  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(14) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 43  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(11) = '1') AND (BE(1) = '1')) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 41  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(11) = '1') AND (BE(0) = '1')) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 37  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(10) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 33  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(9) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 31  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(8) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 27  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(7) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 25  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(6) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 21  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(5) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 17  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(4) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 15  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(3) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 9  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(1) = '1') AND ((BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 5  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(1) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 135  "((CS = '1') AND (READ = '1') AND (REG_SEL(38) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 133  "((CS = '1') AND (READ = '1') AND (REG_SEL(37) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 131  "((CS = '1') AND (READ = '1') AND (REG_SEL(36) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 129  "((CS = '1') AND (READ = '1') AND (REG_SEL(35) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 127  "((CS = '1') AND (READ = '1') AND (REG_SEL(34) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 125  "((CS = '1') AND (READ = '1') AND (REG_SEL(33) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 123  "((CS = '1') AND (READ = '1') AND (REG_SEL(32) = '1') AND ((BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 119  "((CS = '1') AND (READ = '1') AND (REG_SEL(32) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 118  "((CS = '1') AND (READ = '1') AND (REG_SEL(31) = '1') AND (BE(3) = '1')) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 117  "((CS = '1') AND (READ = '1') AND (REG_SEL(31) = '1') AND (BE(2) = '1')) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 116  "((CS = '1') AND (READ = '1') AND (REG_SEL(31) = '1') AND (BE(1) = '1')) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 115  "((CS = '1') AND (READ = '1') AND (REG_SEL(31) = '1') AND (BE(0) = '1')) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 113  "((CS = '1') AND (READ = '1') AND (REG_SEL(30) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 109  "((CS = '1') AND (READ = '1') AND (REG_SEL(29) = '1') AND ((BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 105  "((CS = '1') AND (READ = '1') AND (REG_SEL(28) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 103  "((CS = '1') AND (READ = '1') AND (REG_SEL(27) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 102  "((CS = '1') AND (READ = '1') AND (REG_SEL(26) = '1') AND (BE(2) = '1')) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 99  "((CS = '1') AND (READ = '1') AND (REG_SEL(26) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 97  "((CS = '1') AND (READ = '1') AND (REG_SEL(25) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 95  "((CS = '1') AND (READ = '1') AND (REG_SEL(24) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 93  "((CS = '1') AND (READ = '1') AND (REG_SEL(23) = '1') AND ((BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 91  "((CS = '1') AND (READ = '1') AND (REG_SEL(23) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 87  "((CS = '1') AND (READ = '1') AND (REG_SEL(22) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 83  "((CS = '1') AND (READ = '1') AND (REG_SEL(21) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 79  "((CS = '1') AND (READ = '1') AND (REG_SEL(20) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 75  "((CS = '1') AND (READ = '1') AND (REG_SEL(19) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 71  "((CS = '1') AND (READ = '1') AND (REG_SEL(18) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 67  "((CS = '1') AND (READ = '1') AND (REG_SEL(17) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 63  "((CS = '1') AND (READ = '1') AND (REG_SEL(16) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 59  "((CS = '1') AND (READ = '1') AND (REG_SEL(15) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 53  "((CS = '1') AND (READ = '1') AND (REG_SEL(13) = '1') AND ((BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 51  "((CS = '1') AND (READ = '1') AND (REG_SEL(13) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 49  "((CS = '1') AND (READ = '1') AND (REG_SEL(12) = '1') AND ((BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 47  "((CS = '1') AND (READ = '1') AND (REG_SEL(12) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 44  "((CS = '1') AND (READ = '1') AND (REG_SEL(11) = '1') AND (BE(1) = '1')) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 42  "((CS = '1') AND (READ = '1') AND (REG_SEL(11) = '1') AND (BE(0) = '1')) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 45  "((CS = '1') AND (READ = '1') AND (REG_SEL(11) = '1') AND ((BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 39  "((CS = '1') AND (READ = '1') AND (REG_SEL(10) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 35  "((CS = '1') AND (READ = '1') AND (REG_SEL(9) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 29  "((CS = '1') AND (READ = '1') AND (REG_SEL(7) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 23  "((CS = '1') AND (READ = '1') AND (REG_SEL(5) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 19  "((CS = '1') AND (READ = '1') AND (REG_SEL(4) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 13  "((CS = '1') AND (READ = '1') AND (REG_SEL(2) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 11  "((CS = '1') AND (READ = '1') AND (REG_SEL(1) = '1') AND ((BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 7  "((CS = '1') AND (READ = '1') AND (REG_SEL(1) = '1') AND ((BE(0) = '1') OR (BE(1) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 3  "((CS = '1') AND (READ = '1') AND (REG_SEL(0) = '1') AND ((BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
CHECKSUM: "2066169441 3555927969"
INSTANCE: TB_TOP_CTU_CAN_FD.DUT.MEMORY_REGISTERS_INST.TEST_REGISTERS_GEN_TRUE.TEST_REGISTERS_REG_MAP_COMP
ANNOTATION: " PSLs are excluded "
Condition 3  "((CS = '1') AND (READ = '1') AND (REG_SEL(0) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 9  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(2) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 5  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(1) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 1  "((CS = '1') AND (WRITE = '1') AND (REG_SEL(0) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 13  "((CS = '1') AND (READ = '1') AND (REG_SEL(3) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 11  "((CS = '1') AND (READ = '1') AND (REG_SEL(2) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
ANNOTATION: " PSLs are excluded "
Condition 7  "((CS = '1') AND (READ = '1') AND (REG_SEL(1) = '1') AND ((BE(0) = '1') OR (BE(1) = '1') OR (BE(2) = '1') OR (BE(3) = '1'))) 1 -1"
