simulator: vcs
simulation_resolution: fs

check_elab_log: true

test_name_strategy: generic_parameter
test_name_generic: test_name

compile_debug: false

coverage: true

# VCS has a bug. When toggle coverage on VHDL design is collected,
# and `-exitcode` switch is used, the simulation will return non-zero
# exit code even if no assertions has failed! Simply disabling coverage
# will make the exit code zero. We want to collect coverage, and still
# don't want the exit code bug to corrupt our test result! CTU CAN FD
# testbench reports all errors with "report" with error severity. These
# are caught by the flow even without exit code check! Thus it is safe
# to disable its check
check_exit_code: false

# This is to propagate seed to the TB
seed_generic: seed

comp_options:
    ghdl: "-fpsl -frelaxed-rules --ieee=synopsys"

elab_options:
    vcs: "+warn=noDUP_PARM_ASSGN"
    ghdl: "-Wl,-no-pie -fpsl -frelaxed-rules --ieee=synopsys"

sim_options:
    ghdl: "--ieee-asserts=disable"

generics:
    finish_on_error: 0

targets:

    rtl_ctu_can_fd:
        top_entity: ctu_can_fd_rtl.can_top_level
        source_list_files:
            - src/slf_rtl.yml

    # RTL DUT + Vunit TB
    tb_ctu_can_fd_rtl_vunit:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        source_list_files:
            - rtl_ctu_can_fd
            - test/slf_tb_dependencies_vunit.yml
            - test/slf_tb_common.yml
            - test/slf_tb_top_vunit.yml

    # RTL DUT + Simple TB (no VUnit)
    tb_ctu_can_fd_rtl_simple:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        source_list_files:
            - rtl_ctu_can_fd
            - test/slf_tb_dependencies_simple.yml
            - test/slf_tb_common.yml
            - test/slf_tb_top_simple.yml

    # Xilinx Gate DUT + Vunit TB
    tb_ctu_can_fd_gate_vunit:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        source_list_files:
            # RTL is needed for gates to due to packages!! Netlist is compiled to different
            # library to avoid conflicts
            - rtl_ctu_can_fd
            - test/slf_gate_xilinx_netlist.yml
            - test/slf_tb_dependencies_vunit.yml
            - test/slf_tb_common.yml
            - test/slf_tb_top_gates.yml


    ###############################################################################################
    # Fast ASIC configuration
    ###############################################################################################
    tb_rtl_test_fast_asic:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        test_list_file: test/tlf_fast_asic.yml
        generics:
            # Test-bench configuration
            #log_level: info
            #debug: false
            test_type: feature
            iterations: 1
            timeout: 100 ms
            seed: 0 # No randomization

            # DUT generics
            rx_buffer_size: 64
            txt_buffer_count: 8
            sup_filtA: true
            sup_filtB: true
            sup_filtC: true
            sup_range: true
            sup_traffic_ctrs: true
            sup_parity: true

            # C_TECH_ASIC
            target_technology: 0

            # DUT Bit timing settings
            # (Applies for compliance tests and feature tests!)
            cfg_brp: 2
            cfg_prop: 5
            cfg_ph_1: 7
            cfg_ph_2: 7
            cfg_sjw: 5

            cfg_brp_fd: 1
            cfg_prop_fd: 5
            cfg_ph_1_fd: 7
            cfg_ph_2_fd: 7
            cfg_sjw_fd: 5

            # Clock configuration
            # (Applies for compliance tests and feature tests!)
            cfg_sys_clk_period: 10 ns

            # Number of frames used from each dataset, 1000 means whole dataset
            # These take really long time, so we run only few frames here!
            reference_iterations: 10

        source_list_files:
            - $CTU_TB_TOP_TARGET


    ###############################################################################################
    # Fast FPGA configuration
    ###############################################################################################
    tb_rtl_test_fast_fpga:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        test_list_file: test/tlf_fast_fpga.yml
        generics:
            #log_level: info
            #error_tolerance: 0
            #debug: false
            test_type: feature
            iterations: 1
            timeout: 100 ms
            seed: 0 # No randomization

            # DUT generics
            rx_buffer_size: 64
            txt_buffer_count: 8
            sup_filtA: true
            sup_filtB: true
            sup_filtC: true
            sup_range: true
            sup_traffic_ctrs: true
            sup_parity: true

            # C_TECH_FPGA
            target_technology: 1

            # DUT Bit timing settings
            # (Applies for compliance tests and feature tests!)
            cfg_brp: 2
            cfg_prop: 5
            cfg_ph_1: 7
            cfg_ph_2: 7
            cfg_sjw: 5

            cfg_brp_fd: 1
            cfg_prop_fd: 5
            cfg_ph_1_fd: 7
            cfg_ph_2_fd: 7
            cfg_sjw_fd: 5

            # Clock configuration
            # (Applies for compliance tests and feature tests!)
            cfg_sys_clk_period: 10 ns

            # Number of frames used from each dataset, 1000 means whole dataset
            # These take really long time, so we run only few frames here!
            reference_iterations: 10

        source_list_files:
            - $CTU_TB_TOP_TARGET


    ###############################################################################################
    # Nightly configuration
    ###############################################################################################
    tb_rtl_test_nightly:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        test_list_file: test/tlf_nightly.yml
        generics:
            # Test-bench configuration
            #log_level: info
            #error_tolerance: 0
            #debug: true
            iterations: 1
            timeout: 100 ms
            test_type: feature

            # DUT generics
            rx_buffer_size: 64
            txt_buffer_count: 8
            sup_filtA: true
            sup_filtB: true
            sup_filtC: true
            sup_range: true
            sup_traffic_ctrs: true
            sup_parity: true
            target_technology: 0 # C_TECH_ASIC

            # DUT Bit timing settings
            # Applies for compliance tests and feature tests!
            cfg_brp: 2
            cfg_prop: 5
            cfg_ph_1: 7
            cfg_ph_2: 7
            cfg_sjw: 5

            cfg_brp_fd: 1
            cfg_prop_fd: 5
            cfg_ph_1_fd: 5
            cfg_ph_2_fd: 5
            cfg_sjw_fd: 3

            # Clock configuration
            cfg_sys_clk_period: 10 ns

            # Number of frames used from each dataset, 1000 means whole dataset
            # With unified TB architecture, these run quite long! Therefore we
            # run only sub-set. Then agent will randomize starting position within
            # the data-set, so all-together we pick random:
            #   50 * 10 = 500 (out of 10000) frames
            reference_iterations: 50

        source_list_files:
            - $CTU_TB_TOP_TARGET

    ###############################################################################################
    # Compliance tests - Short run
    ###############################################################################################
    tb_rtl_test_compliance_short:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        test_list_file: test/tlf_compliance_short.yml
        generics:
            #log_level: info
            #error_tolerance: 0
            #debug: false
            iterations: 1
            timeout: 100 ms
            test_type: compliance
            seed: 0 # No randomization

            # DUT generics
            rx_buffer_size: 64
            txt_buffer_count: 2
            sup_filtA: false
            sup_filtB: false
            sup_filtC: false
            sup_range: false
            sup_traffic_ctrs: false
            sup_parity: false
            target_technology: 0 # C_TECH_ASIC

            # DUT Bit timing settings
            # Applies for compliance tests and feature tests!
            cfg_brp: 1
            cfg_prop: 5
            cfg_ph_1: 7
            cfg_ph_2: 7
            cfg_sjw: 4

            cfg_brp_fd: 1
            cfg_prop_fd: 3
            cfg_ph_1_fd: 3
            cfg_ph_2_fd: 3
            cfg_sjw_fd: 2

            # Clock configuration
            cfg_sys_clk_period: 25 ns

        sim_options:
            ghdl: "--vpi=main_tb/iso-16845-compliance-tests/build/Debug/src/cosimulation/libGHDL_VPI_COSIM_LIB.so"
            vcs: "-vhpi VCS_VHPI_COSIM_LIB:handle_register"

        source_list_files:
            - $CTU_TB_TOP_TARGET

    ###############################################################################################
    # Compliance tests - Typical bit-rate
    ###############################################################################################
    tb_rtl_test_compliance_full_typ:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        test_list_file: test/tlf_compliance_full_typ.yml
        generics:
            #log_level: info
            #error_tolerance: 0
            #debug: false
            iterations: 1
            timeout: 200 ms
            test_type: compliance

            # DUT generics
            rx_buffer_size: 64
            txt_buffer_count: 2
            sup_filtA: false
            sup_filtB: false
            sup_filtC: false
            sup_range: false
            sup_traffic_ctrs: false
            sup_parity: false
            target_technology: 0 # C_TECH_ASIC

            # DUT Bit timing settings
            # Applies for compliance tests and feature tests!
            cfg_brp: 4
            cfg_prop: 5
            cfg_ph_1: 7
            cfg_ph_2: 7
            cfg_sjw: 5

            cfg_brp_fd: 1
            cfg_prop_fd: 5
            cfg_ph_1_fd: 7
            cfg_ph_2_fd: 7
            cfg_sjw_fd: 5

            # Clock configuration
            cfg_sys_clk_period: 25 ns

        sim_options:
            ghdl: "--vpi=main_tb/iso-16845-compliance-tests/build/Debug/src/cosimulation/libGHDL_VPI_COSIM_LIB.so"
            vcs: "-vhpi VCS_VHPI_COSIM_LIB:handle_register"

        source_list_files:
            - $CTU_TB_TOP_TARGET

    ###############################################################################################
    # Compliance tests - Minimal bit-rate with maximal phase lengths
    ###############################################################################################
    tb_rtl_test_compliance_full_min_phases:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        test_list_file: test/tlf_compliance_full_min_phases.yml
        generics:
            # Test-bench configuration
            #log_level: info
            #error_tolerance: 0
            #debug: false
            iterations: 1
            timeout: 500 ms
            test_type: compliance

            # DUT generics
            rx_buffer_size: 64
            txt_buffer_count: 2
            sup_filtA: false
            sup_filtB: false
            sup_filtC: false
            sup_range: false
            sup_traffic_ctrs: false
            sup_parity: false
            target_technology: 0 # C_TECH_ASIC

            # DUT Bit timing settings
            # Applies for compliance tests and feature tests!
            cfg_brp: 4
            cfg_prop: 63
            cfg_ph_1: 63
            cfg_ph_2: 63
            cfg_sjw: 31

            cfg_brp_fd: 4
            cfg_prop_fd: 63
            cfg_ph_1_fd: 31
            cfg_ph_2_fd: 31
            cfg_sjw_fd: 31

            # Clock configuration
            cfg_sys_clk_period: 5 ns

        sim_options:
            ghdl: "--vpi=main_tb/iso-16845-compliance-tests/build/Debug/src/cosimulation/libGHDL_VPI_COSIM_LIB.so"
            vcs: "-vhpi VCS_VHPI_COSIM_LIB:handle_register"

        source_list_files:
            - $CTU_TB_TOP_TARGET


    ###############################################################################################
    # Compliance tests - Minimal bit-rate with maximal prescaler
    ###############################################################################################
    tb_rtl_test_compliance_full_min_prescaler:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        test_list_file: test/tlf_compliance_full_min_prescaler.yml
        generics:
            # Test-bench configuration
            #log_level: info
            #error_tolerance: 0
            #debug: false
            iterations: 1
            timeout: 500 ms
            test_type: compliance

            # DUT generics
            rx_buffer_size: 64
            txt_buffer_count: 2
            sup_filtA: false
            sup_filtB: false
            sup_filtC: false
            sup_range: false
            sup_traffic_ctrs: false
            sup_parity: false
            target_technology: 0 # C_TECH_ASIC

            # DUT Bit timing settings
            # Applies for compliance tests and feature tests!
            cfg_brp: 255
            cfg_prop: 1
            cfg_ph_1: 2
            cfg_ph_2: 2
            cfg_sjw: 2

            cfg_brp_fd: 255
            cfg_prop_fd: 1
            cfg_ph_1_fd: 2
            cfg_ph_2_fd: 2
            cfg_sjw_fd: 2

            # Clock configuration
            cfg_sys_clk_period: 5 ns

        sim_options:
            ghdl: "--vpi=main_tb/iso-16845-compliance-tests/build/Debug/src/cosimulation/libGHDL_VPI_COSIM_LIB.so"
            vcs: "-vhpi VCS_VHPI_COSIM_LIB:handle_register"

        source_list_files:
            - $CTU_TB_TOP_TARGET

    ###############################################################################################
    # Compliance tests - Maximal bit-rate
    ###############################################################################################
    tb_rtl_test_compliance_full_max:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        test_list_file: test/tlf_compliance_full_max.yml
        generics:
            #log_level: info
            #error_tolerance: 0
            #debug: false
            iterations: 1
            timeout: 100 ms
            test_type: compliance

            # DUT generics
            rx_buffer_size: 64
            txt_buffer_count: 2
            sup_filtA: false
            sup_filtB: false
            sup_filtC: false
            sup_range: false
            sup_traffic_ctrs: false
            sup_parity: false
            target_technology: 0 # C_TECH_ASIC

            # DUT Bit timing settings
            # Applies for compliance tests and feature tests!
            cfg_brp: 1
            cfg_prop: 1
            cfg_ph_1: 3
            cfg_ph_2: 3
            cfg_sjw: 3

            cfg_brp_fd: 1
            cfg_prop_fd: 0
            cfg_ph_1_fd: 2
            cfg_ph_2_fd: 2
            cfg_sjw_fd: 2

            # Clock configuration
            cfg_sys_clk_period: 25 ns

        sim_options:
            ghdl: "--vpi=main_tb/iso-16845-compliance-tests/build/Debug/src/cosimulation/libGHDL_VPI_COSIM_LIB.so"
            vcs: "-vhpi VCS_VHPI_COSIM_LIB:handle_register"

        source_list_files:
            - $CTU_TB_TOP_TARGET


    ###############################################################################################
    # Xilinx Unisim Gates - Simple feature tests - Vunit ONLY!
    ###############################################################################################
    tb_gate_xilinx_test_simple:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        test_list_file: test/tlf_gates_xilinx_simple.yml
        generics:
            #log_level: info
            #error_tolerance: 0
            #debug: false
            iterations: 1
            timeout: 100 ms

            # DUT generics
            rx_buffer_size: 128
            txt_buffer_count: 4
            sup_filtA: true
            sup_filtB: false
            sup_filtC: false
            sup_range: false
            sup_traffic_ctrs: true
            sup_parity: true

            # Target technology is don't care is Gate config
            #target_technology: 0

            # DUT Bit timing settings
            # (Applies for compliance tests and feature tests!)
            cfg_brp: 2
            cfg_prop: 5
            cfg_ph_1: 7
            cfg_ph_2: 7
            cfg_sjw: 5

            cfg_brp_fd: 1
            cfg_prop_fd: 5
            cfg_ph_1_fd: 7
            cfg_ph_2_fd: 7
            cfg_sjw_fd: 5

            # Clock configuration
            # (Applies for compliance tests and feature tests!)
            cfg_sys_clk_period: 10 ns

            # Number of frames used from each dataset, 1000 means whole dataset
            # These take really long time, so we run only few frames here!
            reference_iterations: 10

        source_list_files:
            - tb_ctu_can_fd_gate_vunit

    ###############################################################################################
    # Xilinx Unisim Gates - Simple compliance tests - Vunit ONLY!
    ###############################################################################################
    tb_gate_xilinx_test_compliance:
        top_entity: ctu_can_fd_tb.TB_TOP_CTU_CAN_FD
        test_list_file: test/tlf_gates_xilinx_compliance.yml
        generics:
            #log_level: info
            #error_tolerance: 0
            #debug: false
            iterations: 1
            timeout: 100 ms
            test_type: compliance

            # DUT generics
            rx_buffer_size: 128
            txt_buffer_count: 4
            sup_filtA: true
            sup_filtB: false
            sup_filtC: false
            sup_range: false
            sup_traffic_ctrs: true
            sup_parity: false

            # DUT Bit timing settings
            # Applies for compliance tests and feature tests!
            cfg_brp: 1
            cfg_prop: 5
            cfg_ph_1: 7
            cfg_ph_2: 7
            cfg_sjw: 4

            cfg_brp_fd: 1
            cfg_prop_fd: 3
            cfg_ph_1_fd: 3
            cfg_ph_2_fd: 3
            cfg_sjw_fd: 2

            # Clock configuration
            cfg_sys_clk_period: 25 ns

        sim_options:
            ghdl: "--vpi=main_tb/iso-16845-compliance-tests/build/Release/src/simulator_interface/libSIMULATOR_INTERFACE_LIB.so"

        source_list_files:
            - tb_ctu_can_fd_gate_vunit



check_severity: error

license_wait: true
