#!/bin/sh

SCRIP_DIR="$(cd "$0" ; pwd)"

cd "$SCRIP_DIR"

python3 update_reg_map.py --xactSpec ../spec/CTU/ip/CAN_FD_IP_Core/2.1/CAN_FD_IP_Core.2.1.xml \
           --updVHDLPackage True --updHeaderFile True --updLyxDocs True --updRTLRegMap True || exit 1

( cd ../src/memory_registers/generated ; patch < "$SCRIP_DIR/memory_reg.vhd.diff" ) || exit 1
