#!/bin/bash

d="$(dirname "$0")"

# Note: the script uses relative paths and must be called from this directory
cd "$d"
python3 update_reg_map.py --xactSpec ../spec/CTU/ip/CAN_FD_IP_Core/2.1/CAN_FD_IP_Core.2.1.xml \
    --updVHDLPackage True \
    --updHeaderFile True \
    --updLyxDocs True \
    --updRTLRegMap True \
    --updTbPackage True
