name: Check sensitivity lists

on: [pull_request]

jobs:

  Check_sensitivity:
    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/logic-design-services/digital-simulation

    permissions:
      contents: read
      packages: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'

      - name: "Check RTL sensitivity lists"
        run: |
          cd scripts
          ./check_sensitivity_lists.py ../src/slf_rtl.yml
